export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_INGREDIENT_FALIED = "FETCH_INGREDIENT_FALIED"